### ISSUE TITLE
Multiple blogs?

### ISSUE THREAD

**Issue by fullofcaffeine** [novoid/lazyblorg#26]
Does lazyblorg support multiple blog targets out-of-the-box?

**Comment by novoid** [comment]
Hi,
There is no dedicated support for multiple blogs.

However, it can be easily achieved by using different config files: one per blog. Just replace the `config.py` with the different config files for your different blogs. Use different command line parameters `--targetdir` and so forth.

I do have two different blogs in place: the minimal testing blog which is part of the source code repository and my personal blog (which is using the same `config.py`). Probably I should add a command line switch to override the default `config.py` location with a different one. Don't know how hard this is to implement since currently, I just execute the content of `config.py` ...

**Comment by transitracer** [comment]
@novoid any progress on this command line flag?

Alternately, would it be possible to allow setting the config.py variables within an org file somehow? That way, I could have my entire blog be a self-contained org file and not have to fork the repository to maintain my own configuration

**Comment by novoid** [comment]
Hi @transitracer,

I created #30 for the feature request of the command line switch.

The second idea sounds reasonable but since it is not my personal use-case, I won't implement it my own. I'm happy to accept pull requests for it.
