### ISSUE TITLE
end-to-end test wrongfully succeeds in case of changed binary data

### ISSUE THREAD

**Issue by mbeppler** [novoid/lazyblorg#68]
To test for the _missing_ `https:` in the RSS feed I run start_end-to-end-test.sh without a change with the result:

    \n====> Comparing result of end-to-end test ...\n
    grep: (standard input): binary file matches
    End-to-end test: success.
    \n\n           End-to-end tests ended successfully! :-)\n\n

First I thought everything was OK, but found out quickly that some pictures are not equal. For `2017-03-11T18.29.21 Sterne im Baum -- mytag publicvoit - scaled width 300.jpg` the _comparison_ size is 51348 and the _result_ size is 51322. Not sure if this is due different tool defaults and/or version. Never the less, the pictures _look_ the same and also the resolution is. Also the rest of the EXIF data.

The problem is `egrep -vi '(published|updated)'` stopping because it receives binary data from the `diff`. Adding `-a` to egrep, to also force _text_ interpretation, worked - the test fails now.

    \n====> Comparing result of end-to-end test ...\n
    grep: (standard input): binary file matches
    End-to-end test FAILED!   Check result!

Adding `-a` to the grep inside the if would list all changes also with binary data. But I don't think this is useful as lots of gibberish is printed.

As a quick workaround I used changed the `<updated>` tag in _result_ from _comparison_, logged all changed files and printed the diff for the text files. But this needed process substitution - unfortunately not part of POSIX shell.

Not sure what the perfect solution would be.

**Comment by novoid** [comment]
Another great analysis, thanks!

Quite frankly: I don't care for this case. As long as the file is generated, I assume its content is OK. The E2E-tests focus on the generated HTML pages and not on comparing binaries.

You're absolutely right: that's no perfect situation but from my current perspective it's good enough to cover the more important use-cases where, e.g., pandoc changes its Org handling and therefore something is broken deep down in some files I would not realize otherwise.

I hope that you agree here somehow when I close this issue for now. I'll re-think my position when I do face any binary-related issue that got undetected because of that.
