### ISSUE TITLE
Add installing requirements to getting started

### ISSUE THREAD

**Issue by xeruf** [novoid/lazyblorg#72]
After cloning the repo and before running the example invocation, one needs to install the requirements added in https://github.com/novoid/lazyblorg/issues/13 with `pip install -r requirements.txt`. Maybe that could also be part of the `example_invocation.sh` already, though.

**Comment by novoid** [comment]
Thanks for the tip.
Since installing dependencies is the Python way of dealing with this, I assume this is part of the usual process. I should check the README if this should be emphasized more.
It's definitely not part of `example_invocation.sh` because dependencies need to be installed only once and the example invocation is thought to be called many times.
