### ISSUE TITLE
lazyblorg test assumes pwd

### ISSUE THREAD

**Issue by xeruf** [novoid/lazyblorg#76]
when calling it from another directory, it fails:
```sh
❯ tests/lazyblorg_test.sh
============================================= test session starts =============================================
platform linux -- Python 3.10.6, pytest-7.1.3, pluggy-1.0.0
rootdir: /home/janek/data/1-projects/1-personal
plugins: mock-3.8.2
collected 0 items                                                                                             

============================================ no tests ran in 0.00s ============================================
ERROR: file or directory not found: tests/lazyblorg_test.py
```
For a shell script I would tell you to inspect `$0` to get the script location but I don't know about python.

**Comment by novoid** [comment]
Yes, the testing may be implemented in a fragile or stupid way. This is because I lack deeper Python knowledge how it's done properly.

If you do find out how to do this properly, I'm happy to apply a pull request of yours. Until then, execute the test within the test directory as a workaround. Sorry for causing you troubles.
